export const FETCH_USERS = 'FETCH_USERS';
export const SELECT_USER = 'SELECT_USER';
export const FETCH_USER_INSPECTIONS = 'FETCH_USER_INSPECTIONS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
